name: io-agents-cpu
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytorch
  - numpy
  - pandas
  - jupyterlab
  - ipykernel
  - pip:
      - -r Jinyi_paper/requirements.txt
