python v0.py \
  --io-profile-path ../experiments/YOUR_EXPERIMENT/personas_io_drivers_4.csv \
  --normal-profile-path ../experiments/YOUR_EXPERIMENT/personas_normal_users_4.csv \
  --action-mode calibrated \
  --action-probabilities-path ../user_prob/action_probabilities_8.csv \
  --implicit-priors-path ../user_prob/implicit_priors_8.csv \
  --estimate-priors \
  --prior-feed-path ../data/Russia/merged_io.pkl \
  --prior-samples 10 \
  --feed-snapshot-size 25 \
  --calibration-beta 1.0 \
  --action-seed 0 \
  --llm-steps 1